# docker-compose.yml
version: '3.8'

services:
  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development

  # Backend Service (Node.js)
  backend:
    build:
      context: ./backend
    # Pass environment variables from the .env file to the container
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
